// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: metar.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetarService_GetMetar_FullMethodName = "/metar.MetarService/GetMetar"
	MetarService_GetTaf_FullMethodName   = "/metar.MetarService/GetTaf"
)

// MetarServiceClient is the client API for MetarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetarServiceClient interface {
	GetMetar(ctx context.Context, in *MetarQuery, opts ...grpc.CallOption) (*MetarReply, error)
	GetTaf(ctx context.Context, in *TafQuery, opts ...grpc.CallOption) (*TafReply, error)
}

type metarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetarServiceClient(cc grpc.ClientConnInterface) MetarServiceClient {
	return &metarServiceClient{cc}
}

func (c *metarServiceClient) GetMetar(ctx context.Context, in *MetarQuery, opts ...grpc.CallOption) (*MetarReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetarReply)
	err := c.cc.Invoke(ctx, MetarService_GetMetar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metarServiceClient) GetTaf(ctx context.Context, in *TafQuery, opts ...grpc.CallOption) (*TafReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TafReply)
	err := c.cc.Invoke(ctx, MetarService_GetTaf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetarServiceServer is the server API for MetarService service.
// All implementations must embed UnimplementedMetarServiceServer
// for forward compatibility.
type MetarServiceServer interface {
	GetMetar(context.Context, *MetarQuery) (*MetarReply, error)
	GetTaf(context.Context, *TafQuery) (*TafReply, error)
	mustEmbedUnimplementedMetarServiceServer()
}

// UnimplementedMetarServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetarServiceServer struct{}

func (UnimplementedMetarServiceServer) GetMetar(context.Context, *MetarQuery) (*MetarReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetar not implemented")
}
func (UnimplementedMetarServiceServer) GetTaf(context.Context, *TafQuery) (*TafReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaf not implemented")
}
func (UnimplementedMetarServiceServer) mustEmbedUnimplementedMetarServiceServer() {}
func (UnimplementedMetarServiceServer) testEmbeddedByValue()                      {}

// UnsafeMetarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetarServiceServer will
// result in compilation errors.
type UnsafeMetarServiceServer interface {
	mustEmbedUnimplementedMetarServiceServer()
}

func RegisterMetarServiceServer(s grpc.ServiceRegistrar, srv MetarServiceServer) {
	// If the following call pancis, it indicates UnimplementedMetarServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetarService_ServiceDesc, srv)
}

func _MetarService_GetMetar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetarQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetarServiceServer).GetMetar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetarService_GetMetar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetarServiceServer).GetMetar(ctx, req.(*MetarQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetarService_GetTaf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TafQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetarServiceServer).GetTaf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetarService_GetTaf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetarServiceServer).GetTaf(ctx, req.(*TafQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// MetarService_ServiceDesc is the grpc.ServiceDesc for MetarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metar.MetarService",
	HandlerType: (*MetarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetar",
			Handler:    _MetarService_GetMetar_Handler,
		},
		{
			MethodName: "GetTaf",
			Handler:    _MetarService_GetTaf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metar.proto",
}
