// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: metar.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Metar_GetMetar_FullMethodName = "/metar.Metar/GetMetar"
	Metar_GetTaf_FullMethodName   = "/metar.Metar/GetTaf"
)

// MetarClient is the client API for Metar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetarClient interface {
	GetMetar(ctx context.Context, in *MetarQuery, opts ...grpc.CallOption) (*MetarReply, error)
	GetTaf(ctx context.Context, in *TafQuery, opts ...grpc.CallOption) (*TafReply, error)
}

type metarClient struct {
	cc grpc.ClientConnInterface
}

func NewMetarClient(cc grpc.ClientConnInterface) MetarClient {
	return &metarClient{cc}
}

func (c *metarClient) GetMetar(ctx context.Context, in *MetarQuery, opts ...grpc.CallOption) (*MetarReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetarReply)
	err := c.cc.Invoke(ctx, Metar_GetMetar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metarClient) GetTaf(ctx context.Context, in *TafQuery, opts ...grpc.CallOption) (*TafReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TafReply)
	err := c.cc.Invoke(ctx, Metar_GetTaf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetarServer is the server API for Metar service.
// All implementations must embed UnimplementedMetarServer
// for forward compatibility.
type MetarServer interface {
	GetMetar(context.Context, *MetarQuery) (*MetarReply, error)
	GetTaf(context.Context, *TafQuery) (*TafReply, error)
	mustEmbedUnimplementedMetarServer()
}

// UnimplementedMetarServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetarServer struct{}

func (UnimplementedMetarServer) GetMetar(context.Context, *MetarQuery) (*MetarReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetar not implemented")
}
func (UnimplementedMetarServer) GetTaf(context.Context, *TafQuery) (*TafReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaf not implemented")
}
func (UnimplementedMetarServer) mustEmbedUnimplementedMetarServer() {}
func (UnimplementedMetarServer) testEmbeddedByValue()               {}

// UnsafeMetarServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetarServer will
// result in compilation errors.
type UnsafeMetarServer interface {
	mustEmbedUnimplementedMetarServer()
}

func RegisterMetarServer(s grpc.ServiceRegistrar, srv MetarServer) {
	// If the following call pancis, it indicates UnimplementedMetarServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Metar_ServiceDesc, srv)
}

func _Metar_GetMetar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetarQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetarServer).GetMetar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metar_GetMetar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetarServer).GetMetar(ctx, req.(*MetarQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metar_GetTaf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TafQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetarServer).GetTaf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metar_GetTaf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetarServer).GetTaf(ctx, req.(*TafQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// Metar_ServiceDesc is the grpc.ServiceDesc for Metar service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metar_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metar.Metar",
	HandlerType: (*MetarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetar",
			Handler:    _Metar_GetMetar_Handler,
		},
		{
			MethodName: "GetTaf",
			Handler:    _Metar_GetTaf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metar.proto",
}
