// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: metar.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetarQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Icao          []string               `protobuf:"bytes,1,rep,name=icao,proto3" json:"icao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetarQuery) Reset() {
	*x = MetarQuery{}
	mi := &file_metar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetarQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetarQuery) ProtoMessage() {}

func (x *MetarQuery) ProtoReflect() protoreflect.Message {
	mi := &file_metar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetarQuery.ProtoReflect.Descriptor instead.
func (*MetarQuery) Descriptor() ([]byte, []int) {
	return file_metar_proto_rawDescGZIP(), []int{0}
}

func (x *MetarQuery) GetIcao() []string {
	if x != nil {
		return x.Icao
	}
	return nil
}

type MetarReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metar         []string               `protobuf:"bytes,1,rep,name=metar,proto3" json:"metar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetarReply) Reset() {
	*x = MetarReply{}
	mi := &file_metar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetarReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetarReply) ProtoMessage() {}

func (x *MetarReply) ProtoReflect() protoreflect.Message {
	mi := &file_metar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetarReply.ProtoReflect.Descriptor instead.
func (*MetarReply) Descriptor() ([]byte, []int) {
	return file_metar_proto_rawDescGZIP(), []int{1}
}

func (x *MetarReply) GetMetar() []string {
	if x != nil {
		return x.Metar
	}
	return nil
}

type TafQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Icao          []string               `protobuf:"bytes,1,rep,name=icao,proto3" json:"icao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TafQuery) Reset() {
	*x = TafQuery{}
	mi := &file_metar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TafQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TafQuery) ProtoMessage() {}

func (x *TafQuery) ProtoReflect() protoreflect.Message {
	mi := &file_metar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TafQuery.ProtoReflect.Descriptor instead.
func (*TafQuery) Descriptor() ([]byte, []int) {
	return file_metar_proto_rawDescGZIP(), []int{2}
}

func (x *TafQuery) GetIcao() []string {
	if x != nil {
		return x.Icao
	}
	return nil
}

type TafReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Taf           []string               `protobuf:"bytes,1,rep,name=taf,proto3" json:"taf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TafReply) Reset() {
	*x = TafReply{}
	mi := &file_metar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TafReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TafReply) ProtoMessage() {}

func (x *TafReply) ProtoReflect() protoreflect.Message {
	mi := &file_metar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TafReply.ProtoReflect.Descriptor instead.
func (*TafReply) Descriptor() ([]byte, []int) {
	return file_metar_proto_rawDescGZIP(), []int{3}
}

func (x *TafReply) GetTaf() []string {
	if x != nil {
		return x.Taf
	}
	return nil
}

var File_metar_proto protoreflect.FileDescriptor

const file_metar_proto_rawDesc = "" +
	"\n" +
	"\vmetar.proto\x12\x05metar\" \n" +
	"\n" +
	"MetarQuery\x12\x12\n" +
	"\x04icao\x18\x01 \x03(\tR\x04icao\"\"\n" +
	"\n" +
	"MetarReply\x12\x14\n" +
	"\x05metar\x18\x01 \x03(\tR\x05metar\"\x1e\n" +
	"\bTafQuery\x12\x12\n" +
	"\x04icao\x18\x01 \x03(\tR\x04icao\"\x1c\n" +
	"\bTafReply\x12\x10\n" +
	"\x03taf\x18\x01 \x03(\tR\x03taf2e\n" +
	"\x05Metar\x120\n" +
	"\bGetMetar\x12\x11.metar.MetarQuery\x1a\x11.metar.MetarReply\x12*\n" +
	"\x06GetTaf\x12\x0f.metar.TafQuery\x1a\x0f.metar.TafReplyB\x15Z\x13src/interfaces/grpcb\x06proto3"

var (
	file_metar_proto_rawDescOnce sync.Once
	file_metar_proto_rawDescData []byte
)

func file_metar_proto_rawDescGZIP() []byte {
	file_metar_proto_rawDescOnce.Do(func() {
		file_metar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metar_proto_rawDesc), len(file_metar_proto_rawDesc)))
	})
	return file_metar_proto_rawDescData
}

var file_metar_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_metar_proto_goTypes = []any{
	(*MetarQuery)(nil), // 0: metar.MetarQuery
	(*MetarReply)(nil), // 1: metar.MetarReply
	(*TafQuery)(nil),   // 2: metar.TafQuery
	(*TafReply)(nil),   // 3: metar.TafReply
}
var file_metar_proto_depIdxs = []int32{
	0, // 0: metar.Metar.GetMetar:input_type -> metar.MetarQuery
	2, // 1: metar.Metar.GetTaf:input_type -> metar.TafQuery
	1, // 2: metar.Metar.GetMetar:output_type -> metar.MetarReply
	3, // 3: metar.Metar.GetTaf:output_type -> metar.TafReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metar_proto_init() }
func file_metar_proto_init() {
	if File_metar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metar_proto_rawDesc), len(file_metar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metar_proto_goTypes,
		DependencyIndexes: file_metar_proto_depIdxs,
		MessageInfos:      file_metar_proto_msgTypes,
	}.Build()
	File_metar_proto = out.File
	file_metar_proto_goTypes = nil
	file_metar_proto_depIdxs = nil
}
